learning_log/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'',include('llapp1.urls',namespace='llapp1')),
]

llapp1/urls.py
'''定义llapp1的URL'''
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$',views.index,name="index"),
	url(r'^topics/$',views.topics,name="topics"),
	url(r'^topics/(?P<topic_id>\d+)/$',views.topic,name="topic"),
	url(r'^new_topic/$',views.new_topic,name="new_topic"),
	url(r'^new_entry/(?P<topic_id>\d+)/$',views.new_entry,name="new_entry"),
	url(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name="edit_entry")
]

llapp1/models.py
from django.db import models


class Topic(models.Model):
	text = models.CharField(max_length=200)
	add_time = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return self.text

class Entry(models.Model):
	topic = models.ForeignKey(Topic)
	text = models.TextField()
	date_add = models.DateTimeField(auto_now_add=True)

	class Meta:
		verbose_name_plural = "Entries"\

	def __str__(self):
		return self.text[:50]+"..."
# Create your models here.

llapp1/forms.py
from django import forms

from .models import Topic
from .models import Entry

class TopicForm(forms.ModelForm):
	class Meta:
		model = Topic
		fields = ["text"]
		labels = {"text":""}

class	EntryForm(forms.ModelForm):
	class	Meta:
		model = Entry
		fields = ["text"]
		labels = {"text":""}
		widgets = {"text":forms.Textarea(attrs={"cols":80})}

llapp1/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse

from .models import Topic,Entry
from .forms import TopicForm,EntryForm

def index(request):
	"""学习笔记主页"""
	return render(request,"index.html")

def topics(request):
	"""主题（数据库表）"""
	topics = Topic.objects.order_by("add_time")
	context = {"ts":topics}
	return render(request,"topics.html",context)

def topic(request,topic_id):
	"""显示单个主题及其所有的条目(每一个数据记录)"""
	topic = Topic.objects.get(id=topic_id)
	entries = topic.entry_set.order_by("-date_add")
	context = {'topic':topic,'entries':entries}
	return render(request,'topic.html',context)

def	new_topic(request):
	"""用户添加主题"""
	if request.method != "POST":
		form = TopicForm()
	else:
		form = TopicForm(request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse("llapp1:topics"))
	context = {"form":form}
	return render(request,"new_topic.html",context)

def	new_entry(request,topic_id):
	"""在特定的主题中添加条目"""
	topic = Topic.objects.get(id=topic_id)

	if request.method != "POST":
		form = EntryForm()
	else:
		form = EntryForm(data=request.POST)
		if form.is_valid():
			new_entry = form.save(commit=False)
			new_entry.topic = topic
			new_entry.save()
			return HttpResponseRedirect(reverse("llapp1:topic",args=[topic_id]))

	context = {"topic":topic,"form":form}
	return render(request,"new_entry.html",context)

def edit_entry(request,entry_id):
	"""编辑现有的条目"""
	entry = Entry.objects.get(id=entry_id)
	topic = entry.topic

	if request.method != "POST":
		# 初次请求，使用当前条目填充表单
		form = EntryForm(instance=entry)
	else:
		# post提交，对数据进行处理
		form = EntryForm(instance=entry,data=request.POST)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse("llapp1:topic",args=[topic.id]))

	context = {"entry":entry,"topic":topic,"form":form}
	return render(request,"edit_entry.html",context)
# Create your views here.

llapp1/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>
    <a href="{% url 'llapp1:index'%}">Learning Log</a>
    <a href="{%url 'llapp1:topics'%}">Topics</a>
</p>
{%block content%}

{%endblock content%}
</body>
</html>

llapp1/templates/edit_entry.html
{%extends "base.html"%}
{%block content%}
<p><a href="{%url 'llapp1:topic' topic.id%}">{{topic}}</a></p>
<p>Edit entry</p>
<form action="{%url 'llapp1:edit_entry' entry.id%}" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button name="summit">Save Change</button>

</form>

{%endblock content%}

llapp1/templates/index.html
{% extends "base.html"%}

{%block content%}
<p>Learning Log helps you keep track of your learning, for any topic you're
learning about.</p>

{%endblock content%}

llapp1/templates/new_entry.html
{%extends "base.html"%}
{%block content%}
<p><a href="{% url 'llapp1:topic' topic.id %}">{{topic}}</a></p>

<p>Add a new Entry:</p>
<form action="{%url 'llapp1:new_entry' topic.id%}" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button name="summit">add entry</button>
</form>

{%endblock content%}

llapp1/templates/new_topic.html
{%extends "base.html"%}
{%block content%}
<p>Add a new topic:</p>
<form action="{%url 'llapp1:new_topic'%}" method="post">
    {%csrf_token%}
    {{form.as_p}}
    <button name="summit">add topic</button>
</form>
{%endblock content%}

llapp1/templates/topic.html
{%extends 'base.html'%}
{%block content%}
<p>Topic:{{topic}}</p>
<p>Entries:</p>
<ul>
    {%for entry in entries%}
    <li>
    <p>{{entry.date_add|date:'M d,Y H:i'}}</p>
    <p>{{entry.text|linebreaks}}</p>
        <p>
            <a href="{% url 'llapp1:edit_entry' entry.id%}">edit entry</a>
        </p>
    </li>
    {%empty%}
    <li>
    There are no entries for this topic yet.
    </li>
    {%endfor%}
    <a href="{%url 'llapp1:new_entry' topic.id%}">add new entry</a>
</ul>
{%endblock content%}

llapp1/templates/topics.html
{% extends "base.html"%}

{%block content%}
<p>Topics</p>
<ul>
    {%for t in ts%}
        <li>
        <a href = "{%url 'llapp1:topic' t.id %}">{{t}}</a>
        </li>
    {%empty%}
        <li>No topics have been added yet.</li>
    {%endfor%}
</ul>
<a href="{%url 'llapp1:new_topic'%}">Add a topic:</a>

{%endblock content%}